name: systemflow
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - scipy
  - pandas
  - matplotlib
  - networkx
  - openpyxl
  - pip
  - pip:
    - plotly
    - multiprocess
    - kaleido
